//------------------------------------------------------------------------
// Copyright(c) 2022 Steinberg Media Technologies GmbH.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"FretForge Link.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"FretForge Link VST3 (64Bit)"
#else
#define stringFileDescription	"FretForge Link VST3"
#endif
#define stringCompanyName		"FretForge\0"
#define stringLegalCopyright	"Copyright(c) 2026 FretForge."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
